services:
  #database section
  orderdb:
    image: mcr.microsoft.com/mssql/server:2019-latest
  
  productdb:
    image: mysql:8.0.29
  
  customerdb:
    image: postgres:alpine3.16
    
  basketdb:
    image: redis:alpine

  inventorydb:
    image: mongo:6
    platform: linux/amd64

  hangfiredb:
    image: mongo:6

  #infrastructure section
  rabbitmq:
    image: rabbitmq:3-management-alpine
  
  pgadmin:
    image: dpage/pgadmin4

  portainer:
    image: portainer/portainer-ce

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.7

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.7
  
#microservice section
  product.api:
    image: ${DOCKER_REGISTRY-}product.api:${PLATFORM:-linux}-${TAG:-latest}
    build:
        context: .
        dockerfile: Services/Product/Product.API/Dockerfile

  customer.api:
    image: ${DOCKER_REGISTER-}customer.api:${PLATFORM:-linux}-${TAG:-latest}
    build:
        context: .
        dockerfile: Services/Customer/Customer.API/Dockerfile
  
  basket.api:
    image: ${DOCKER_REGISTER-}basket.api:${PLATFORM:-linux}-${TAG:-latest}
    build:
        context: .
        dockerfile: Services/Basket/Basket.API/Dockerfile
  
  ordering.api:
    image: ${DOCKER_REGISTER-}ordering.api:${PLATFORM:-linux}-${TAG:-latest}
    build:
        context: .
        dockerfile: Services/Ordering/Ordering.API/Dockerfile

  inventory.api:
    image: ${DOCKER_REGISTER-}inventory.api:${PLATFORM:-linux}-${TAG:-latest}
    build:
        context: .
        dockerfile: Services/Inventory/Inventory.API/Dockerfile

  apigw.ocelot:
    image: ${DOCKER_REGISTER-}apigw.ocelot:${PLATFORM:-linux}-${TAG:-latest}
    build:
        context: .
        dockerfile: ApiGateways/OcelotApiGw/Dockerfile

  hangfire.api:
    image: ${DOCKER_REGISTER-}hangfire.api:${PLATFORM:-linux}-${TAG:-latest}
    build:
        context: .
        dockerfile: Services/ScheduledJob/Hangfire.API/Dockerfile


#network section
networks:
  default:
    name: tedu_microservice
    driver: bridge

#volumes section
volumes:
  sqlserver_data:
    name: sqlserver_data
  mysql_data:
    name: mysql_data
  postgres_data:
    name: postgres_data
  portainer_data:
    name: portainer_data
  elasticsearch_data:
    name: elasticsearch_data
  jaeger_data:
    name: jaeger_data
  mongo_data:
    name: mongo_data
  pgadmin_data:
    name: pgadmin_data
  hangfire_mongo_data:
    name: hangfire_mongo_data
    